// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_pJrruubr9KRgxcE95usw8SBC8bt3iA',
    appId: '1:889590493882:web:1fcda71a75b7c225288883',
    messagingSenderId: '889590493882',
    projectId: 'note-749e9',
    authDomain: 'note-749e9.firebaseapp.com',
    storageBucket: 'note-749e9.appspot.com',
    measurementId: 'G-Z29R660WXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWIP4_hZ_BR0ozhO55WstP30IR1Qo5oo',
    appId: '1:889590493882:android:267399ccbbe2f2a2288883',
    messagingSenderId: '889590493882',
    projectId: 'note-749e9',
    storageBucket: 'note-749e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYuixwnYyCsnvqO8g7ryobmZB0xR_Iys',
    appId: '1:889590493882:ios:d5c76b2da03ac634288883',
    messagingSenderId: '889590493882',
    projectId: 'note-749e9',
    storageBucket: 'note-749e9.appspot.com',
    iosClientId: '889590493882-9tjlsg02tctjr1idsooj9js347sib6gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYuixwnYyCsnvqO8g7ryobmZB0xR_Iys',
    appId: '1:889590493882:ios:d5c76b2da03ac634288883',
    messagingSenderId: '889590493882',
    projectId: 'note-749e9',
    storageBucket: 'note-749e9.appspot.com',
    iosClientId: '889590493882-9tjlsg02tctjr1idsooj9js347sib6gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
